#!/bin/sh
a
# Source the colors.
# . "${HOME}/.cache/wal/colors.sh"
# Set the border colors.
#bspc config normal_border_color "#a8a19f"
bspc config normal_border_color "#000000"
#bspc config active_border_color "#f22c40"
bspc config active_border_color "#766e6b"
bspc config focused_border_color "#ff0099"
bspc config presel_feedback_color "$color1"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        0
bspc config window_gap          10
bspc config focus_follows_pointer true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	true
# bspc config top_padding 0

#bspc rule -a emacs desktop='^1'
#bspc rule -a qutebrowser desktop='^2'
#bspc rule -a Gimp desktop='^8' state=floating follow=on

# xrdb -merge ~/.extend.Xresources
#compton -r 25 -o .85 -f --backend glx
# Set pointer, so that it's not an X
# xsetroot -cursor_name left_ptr
#polybar main_bar &
# Set cursor shape
xsetroot -cursor_name left_ptr

# Run sxhkd and compton
sxhkd &
compton --config ~/.config/compton/compton.conf &
